#=================================================
# Description: Build OpenWrt using GitHub Actions
#
# Lisence: MIT
#
# Author: Lunseil
#=================================================

name: 编译X86_64

on: 
  release:
    types: [published]
    
  push:
    branches: 
      - main
      
  schedule:
    - cron: 0 21 * * *
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: 初始化环境
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        docker rmi `docker images -q`
        echo "Deleting files, please wait ..."
        sudo rm -rf \
          /usr/share/dotnet \
          /etc/mysql \
          /etc/php
        sudo -E apt-get -y purge \
          azure-cli \
          ghc* \
          zulu* \
          hhvm \
          llvm* \
          firefox \
          google* \
          dotnet* \
          powershell \
          openjdk* \
          mysql* \
          php*
        sudo -E apt-get update
        sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev patch python3 python2.7 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex node-uglify git gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx-ucl libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib antlr3 gperf wget curl swig rsync
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean
        
    - name: 下载Lede源码
      env: 
        REPO_URL: https://github.com/coolsnowwolf/lede
        REPO_BRANCH: master
      run: |
        git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt
        cd openwrt
        sed -i 's/#src-git helloworld/src-git helloworld/g' ./feeds.conf.default
        
    - name: 升级 & 安装 feeds
      working-directory: ./openwrt
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        ./scripts/feeds install -a
        
    - name: 导入第三方插件
      working-directory: ./openwrt
      run: |
        git clone https://github.com/xiaorouji/openwrt-passwall.git package/openwrt-passwall
        git clone https://github.com/281677160/openwrt-package.git package/281677160
  
    - name: argon_new主题
      working-directory: ./openwrt
      run: |
        cd package/lean
        rm -rf luci-theme-argon
        git clone -b 18.06 https://github.com/jerrykuku/luci-theme-argon.git
        
    - name: netdata汉化
      working-directory: ./openwrt
      run: |
        cd package/lean
        rm -rf luci-app-netdata
        git clone https://github.com/sirpdboy/luci-app-netdata.git
        
    - name: 配置自定义
      env:
        CONFIG_FILE: 'x86_64.config'
      run: |
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
        chmod +x ./customize.sh && ./customize.sh
        cd openwrt && make defconfig
        
    - name: 更换banner
      working-directory: ./openwrt
      run: |
        cd package/base-files/files/etc
        sudo rm banner
        wget https://raw.githubusercontent.com/lunseil/AutoBuild-LEDE/master/banner
        
    - name: 预下载DL库
      working-directory: ./openwrt
      run: |
        make download -j$(nproc)
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;
        
    - name: 正式编译固件
      working-directory: ./openwrt
      run: |
        echo -e "$(nproc) thread build."
        make -j$(nproc) V=s
        echo "date=$(date "+%y.%m.%d-%H.%M")" >> $GITHUB_ENV
        echo "date1=$(date "+%Y年%m月%d号-%H点%M分")" >> $GITHUB_ENV
        echo "date2=$(date "+%Y%m%d%H%M%S")" >> $GITHUB_ENV
        
    - name: 删除冗余文件
      working-directory: ./openwrt
      run: |
        cd bin/targets/*/*
        rm -rf packages && mkdir packages
        find -name "*feeds.buildinfo*" | xargs -i mv -f {} packages
        find -name "*version.buildinfo*" | xargs -i mv -f {} packages
        find -name "*sha256sums*" | xargs -i mv -f {} packages
        find -name "*.manifest*" | xargs -i mv -f {} packages
        find -name "*.bin*" | xargs -i mv -f {} packages
        find -name "*.vmdk*" | xargs -i mv -f {} packages
        find -name "*rootfs.img*" | xargs -i mv -f {} packages
        find -name "*tar.gz*" | xargs -i mv -f {} packages
        rm -rf packages
    
    - name: Release zip
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: OpenWrt_Lean_${{ env.date1 }}
        tag_name: ${{ env.date2 }}
        body: |
            ☆  源码 : https://github.com/coolsnowwolf/lede
            
            ☆  分支 : master
            
            ☆  感谢源码作者Lean大神无私分享！
        files: openwrt/bin/targets
        
    - name : 打包上传
      uses: actions/upload-artifact@master
      with:
        name: OpenWrt_Lean_${{ env.date }}
        path: openwrt/bin/targets
